### ISSUE TITLE
CSI - main category is one-class (anomaly) classification

### ISSUE THREAD

**Issue by sangwoomo** [hoya012/awesome-anomaly-detection#22]
Hi @hoya012, thank you for the super awesome repository!

First, thank you for mentioning our paper "CSI: Novelty Detection via Contrastive Learning on Distributionally Shifted Instance" (NeurIPS 2020). However, I want to clarify that our main category is **one-class (anomaly) classification**, while we also provide an extension for (multi-class) OOD detection.

Can you move our paper to the one-class classification (or both one-class and OOD) category?

Thank you for your kind response and valuable efforts!

**Comment by hoya012** [comment]
Sure! Thank you!

**Comment by tommying** [comment]
@sangwoomo , Hi, I have some confused that according to the description in your paper ("CSI: Novelty Detection via Contrastive Learning on Distributionally Shifted Instance" ) , I think OOD and one-class classification are the same thing?

**Comment by sangwoomo** [comment]
Hi @tommying,

As you said, anomaly and OOD are the same thing, but prior works using the OOD terminology focused on detecting out-of-class samples from a classifier. I just wanted to clarify that our work tackles both **with** and **without** additional class labels scenarios!
