### ISSUE TITLE
Add this paper to your repo

### ISSUE THREAD

**Issue by SMSD75** [hoya012/awesome-anomaly-detection#33]
Hi,

This paper has been accepted in CVPR2021. I kindly ask you to add it to your nice repo. 
"Multiresolution Knowledge Distillation for Anomaly Detection" : https://arxiv.org/pdf/2011.11108.pdf

Thanks.

**Comment by ehdrndd** [comment]
Hi,

This paper has been accepted in IEEE 2018. I kindly ask you to add it to your nice repo.
[DeepAnT: A Deep Learning Approach for Unsupervised Anomaly Detection in Time Series](https://ieeexplore.ieee.org/abstract/document/8581424)

for Time Series

**Comment by hoya012** [comment]
I added it! Thanks
