### ISSUE TITLE
Author/Link information is incorrect for paper "Outlier Detection with Autoencoder Ensembles"

### ISSUE THREAD

**Issue by yzhao062** [hoya012/awesome-anomaly-detection#5]
Hi there,

Looks like SDM17 paper has an incorrect author/pdf info.

Chen, J., Sathe, S., Aggarwal, C. and Turaga, D., 2017, June. Outlier detection with autoencoder ensembles. In Proceedings of the 2017 SIAM International Conference on Data Mining (pp. 90-98). Society for Industrial and Applied Mathematics.

pdf: http://saketsathe.net/downloads/autoencode.pdf

Thanks,
Yue

**Comment by hoya012** [comment]
Thank You!
